FROM node:22-alpine AS builder
WORKDIR /app
COPY package*.json ./
RUN npm ci
COPY . .
RUN node ace build

FROM node:22-alpine AS production
WORKDIR /app 
COPY --from=builder /app/build ./
COPY --from=builder /app/node_modules ./node_modules
ENV NODE_ENV=production HOST=0.0.0.0 PORT=3333
EXPOSE 3333
CMD ["node", "bin/server.js"]